# Generated by Django 3.1.7 on 2021-03-21 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scanlator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScanlatorSeriesURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=511)),
                ('scanlator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.scanlator')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.series')),
            ],
        ),
        migrations.AddField(
            model_name='scanlator',
            name='series',
            field=models.ManyToManyField(blank=True, through='manga.ScanlatorSeriesURL', to='manga.Series'),
        ),
    ]
