# Generated by Django 3.1.7 on 2021-03-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanlator',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
