# Generated by Django 3.1.7 on 2021-03-21 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_auto_20210320_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanlatorSeriesURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=511)),
                ('scanlator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manga.scanlator')),
                ('series', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manga.series')),
            ],
        ),
    ]
