# Generated by Django 3.1.7 on 2021-03-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_scanlatorseriesurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanlator',
            name='series',
            field=models.ManyToManyField(blank=True, to='manga.Series'),
        ),
        migrations.AlterField(
            model_name='scanlator',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
